Error connecting to database: Error: Access denied for user ''@'localhost' (using password: NO)
    at Packet.asError (/home/timefor4/nodevenv/repositories/FPL_API/20/lib/node_modules/mysql2/lib/packets/packet.js:740:17)
    at ClientHandshake.execute (/home/timefor4/nodevenv/repositories/FPL_API/20/lib/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/home/timefor4/nodevenv/repositories/FPL_API/20/lib/node_modules/mysql2/lib/base/connection.js:475:34)
    at PacketParser.onPacket (/home/timefor4/nodevenv/repositories/FPL_API/20/lib/node_modules/mysql2/lib/base/connection.js:93:12)
    at PacketParser.executeStart (/home/timefor4/nodevenv/repositories/FPL_API/20/lib/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/timefor4/nodevenv/repositories/FPL_API/20/lib/node_modules/mysql2/lib/base/connection.js:100:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
